// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqs/pools/v1beta1/pools.proto

package pools

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	v1beta1 "github.com/osmosis-labs/sqs/pkg/api/v1beta1"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IncentiveType represents the type of incentive for the pool.
type IncentiveType int32

const (
	IncentiveType_SUPERFLUID IncentiveType = 0
	IncentiveType_OSMOSIS    IncentiveType = 1
	IncentiveType_BOOST      IncentiveType = 2
	IncentiveType_NONE       IncentiveType = 3
)

var IncentiveType_name = map[int32]string{
	0: "SUPERFLUID",
	1: "OSMOSIS",
	2: "BOOST",
	3: "NONE",
}

var IncentiveType_value = map[string]int32{
	"SUPERFLUID": 0,
	"OSMOSIS":    1,
	"BOOST":      2,
	"NONE":       3,
}

func (x IncentiveType) String() string {
	return proto.EnumName(IncentiveType_name, int32(x))
}

func (IncentiveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30f2696e6c186971, []int{0}
}

// GetPoolsFilter is the filter type for querying pools.
// It is used to filter pools based on the provided fields.
type GetPoolsRequestFilter struct {
	// pool_id is the pool id to query. If not provided, will return all pools.
	PoolId []uint64 `protobuf:"varint,1,rep,packed,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// pool_id_not_in is the list of pool id to exclude from the query.
	PoolIdNotIn []uint64 `protobuf:"varint,2,rep,packed,name=pool_id_not_in,json=poolIdNotIn,proto3" json:"pool_id_not_in,omitempty"`
	// type is the pool type to filter pools by.
	Type []uint64 `protobuf:"varint,3,rep,packed,name=type,proto3" json:"type,omitempty"`
	// incentive is the incentive to filter pools by.
	Incentive []IncentiveType `protobuf:"varint,4,rep,packed,name=incentive,proto3,enum=sqs.pools.v1beta1.IncentiveType" json:"incentive,omitempty"`
	// min_liquidity_cap is the minimum liquidity cap to filter pools by.
	MinLiquidityCap uint64 `protobuf:"varint,5,opt,name=min_liquidity_cap,json=minLiquidityCap,proto3" json:"min_liquidity_cap,omitempty"`
	// with_market_incentives indicates whether to include incentives into pools
	// response.
	WithMarketIncentives bool `protobuf:"varint,6,opt,name=with_market_incentives,json=withMarketIncentives,proto3" json:"with_market_incentives,omitempty"`
	// denom is the list of denominations to filter pools by.
	Denom []string `protobuf:"bytes,7,rep,name=denom,proto3" json:"denom,omitempty"`
	// search is the search string to filter pools by.
	Search string `protobuf:"bytes,8,opt,name=search,proto3" json:"search,omitempty"`
}

func (m *GetPoolsRequestFilter) Reset()         { *m = GetPoolsRequestFilter{} }
func (m *GetPoolsRequestFilter) String() string { return proto.CompactTextString(m) }
func (*GetPoolsRequestFilter) ProtoMessage()    {}
func (*GetPoolsRequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_30f2696e6c186971, []int{0}
}
func (m *GetPoolsRequestFilter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPoolsRequestFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPoolsRequestFilter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetPoolsRequestFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolsRequestFilter.Merge(m, src)
}
func (m *GetPoolsRequestFilter) XXX_Size() int {
	return m.Size()
}
func (m *GetPoolsRequestFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolsRequestFilter.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolsRequestFilter proto.InternalMessageInfo

func (m *GetPoolsRequestFilter) GetPoolId() []uint64 {
	if m != nil {
		return m.PoolId
	}
	return nil
}

func (m *GetPoolsRequestFilter) GetPoolIdNotIn() []uint64 {
	if m != nil {
		return m.PoolIdNotIn
	}
	return nil
}

func (m *GetPoolsRequestFilter) GetType() []uint64 {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *GetPoolsRequestFilter) GetIncentive() []IncentiveType {
	if m != nil {
		return m.Incentive
	}
	return nil
}

func (m *GetPoolsRequestFilter) GetMinLiquidityCap() uint64 {
	if m != nil {
		return m.MinLiquidityCap
	}
	return 0
}

func (m *GetPoolsRequestFilter) GetWithMarketIncentives() bool {
	if m != nil {
		return m.WithMarketIncentives
	}
	return false
}

func (m *GetPoolsRequestFilter) GetDenom() []string {
	if m != nil {
		return m.Denom
	}
	return nil
}

func (m *GetPoolsRequestFilter) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

// GetPoolsRequest is the request type for the Service.Get RPC method.
type GetPoolsRequest struct {
	// Filter options for the result set
	Filter *GetPoolsRequestFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Pagination options for the result set
	Pagination *v1beta1.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Sort options for the result set
	Sort *v1beta1.SortRequest `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (m *GetPoolsRequest) Reset()         { *m = GetPoolsRequest{} }
func (m *GetPoolsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPoolsRequest) ProtoMessage()    {}
func (*GetPoolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30f2696e6c186971, []int{1}
}
func (m *GetPoolsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPoolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPoolsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetPoolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolsRequest.Merge(m, src)
}
func (m *GetPoolsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetPoolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolsRequest proto.InternalMessageInfo

func (m *GetPoolsRequest) GetFilter() *GetPoolsRequestFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *GetPoolsRequest) GetPagination() *v1beta1.PaginationRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetPoolsRequest) GetSort() *v1beta1.SortRequest {
	if m != nil {
		return m.Sort
	}
	return nil
}

// TODO: Add more fields to the response
type GetPoolsResponse struct {
}

func (m *GetPoolsResponse) Reset()         { *m = GetPoolsResponse{} }
func (m *GetPoolsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPoolsResponse) ProtoMessage()    {}
func (*GetPoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30f2696e6c186971, []int{2}
}
func (m *GetPoolsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPoolsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetPoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolsResponse.Merge(m, src)
}
func (m *GetPoolsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetPoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("sqs.pools.v1beta1.IncentiveType", IncentiveType_name, IncentiveType_value)
	proto.RegisterType((*GetPoolsRequestFilter)(nil), "sqs.pools.v1beta1.GetPoolsRequestFilter")
	proto.RegisterType((*GetPoolsRequest)(nil), "sqs.pools.v1beta1.GetPoolsRequest")
	proto.RegisterType((*GetPoolsResponse)(nil), "sqs.pools.v1beta1.GetPoolsResponse")
}

func init() { proto.RegisterFile("sqs/pools/v1beta1/pools.proto", fileDescriptor_30f2696e6c186971) }

var fileDescriptor_30f2696e6c186971 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6f, 0xda, 0x30,
	0x18, 0xc6, 0x31, 0x49, 0xf9, 0xf3, 0xa2, 0x51, 0x6a, 0x75, 0x9d, 0x55, 0x6d, 0x51, 0xc4, 0x76,
	0x88, 0x2a, 0x0d, 0x04, 0xdb, 0x79, 0xda, 0xba, 0xb6, 0x13, 0x5a, 0x0b, 0x28, 0x69, 0x2f, 0xbb,
	0x44, 0x01, 0x3c, 0xb0, 0x4a, 0xec, 0x10, 0x9b, 0x4e, 0x7c, 0x8b, 0x7d, 0x9d, 0x7d, 0x83, 0x5d,
	0x26, 0xf5, 0xb8, 0xe3, 0x04, 0x5f, 0x64, 0x8a, 0x13, 0x60, 0x5d, 0xb9, 0xe5, 0xf5, 0xf3, 0xfe,
	0x1e, 0xdb, 0xef, 0x13, 0xc3, 0x0b, 0x39, 0x93, 0xcd, 0x48, 0x88, 0xa9, 0x6c, 0xde, 0xb5, 0x06,
	0x54, 0x05, 0xad, 0xb4, 0x6a, 0x44, 0xb1, 0x50, 0x02, 0x1f, 0xc8, 0x99, 0x6c, 0xa4, 0x0b, 0x99,
	0x7c, 0x5c, 0x4f, 0x88, 0xd9, 0x9c, 0xc6, 0x8b, 0x2d, 0x11, 0x8c, 0x19, 0x0f, 0x14, 0x13, 0x3c,
	0xc5, 0x8e, 0x9f, 0x3f, 0xee, 0x91, 0x22, 0x56, 0xa9, 0x5a, 0xff, 0x91, 0x87, 0xa7, 0x9f, 0xa8,
	0xea, 0x27, 0xb6, 0x2e, 0x9d, 0xcd, 0xa9, 0x54, 0x17, 0x6c, 0xaa, 0x68, 0x8c, 0x9f, 0x41, 0x31,
	0xd9, 0xcc, 0x67, 0x23, 0x82, 0x6c, 0xc3, 0x31, 0xdd, 0x42, 0x52, 0x76, 0x46, 0xf8, 0x25, 0x54,
	0x33, 0xc1, 0xe7, 0x42, 0xf9, 0x8c, 0x93, 0xbc, 0xd6, 0x2b, 0xa9, 0xde, 0x15, 0xaa, 0xc3, 0x31,
	0x06, 0x53, 0x2d, 0x22, 0x4a, 0x0c, 0x2d, 0xe9, 0x6f, 0xfc, 0x0e, 0xca, 0x8c, 0x0f, 0x29, 0x57,
	0xec, 0x8e, 0x12, 0xd3, 0x36, 0x9c, 0x6a, 0xdb, 0x6e, 0x3c, 0xba, 0x54, 0xa3, 0xb3, 0xee, 0xb9,
	0x5e, 0x44, 0xd4, 0xdd, 0x22, 0xf8, 0x04, 0x0e, 0x42, 0xc6, 0xfd, 0x29, 0x9b, 0xcd, 0xd9, 0x88,
	0xa9, 0x85, 0x3f, 0x0c, 0x22, 0xb2, 0x67, 0x23, 0xc7, 0x74, 0xf7, 0x43, 0xc6, 0x2f, 0xd7, 0xeb,
	0x1f, 0x83, 0x08, 0xbf, 0x85, 0xa3, 0x6f, 0x4c, 0x4d, 0xfc, 0x30, 0x88, 0x6f, 0x69, 0x72, 0xc8,
	0xcc, 0x44, 0x92, 0x82, 0x8d, 0x9c, 0x92, 0x7b, 0x98, 0xa8, 0x57, 0x5a, 0xdc, 0xec, 0x27, 0xf1,
	0x21, 0xec, 0x8d, 0x28, 0x17, 0x21, 0x29, 0xda, 0x86, 0x53, 0x76, 0xd3, 0x02, 0x1f, 0x41, 0x41,
	0xd2, 0x20, 0x1e, 0x4e, 0x48, 0xc9, 0x46, 0x4e, 0xd9, 0xcd, 0xaa, 0xfa, 0x2f, 0x04, 0xfb, 0xff,
	0xcd, 0x0e, 0xbf, 0x87, 0xc2, 0x57, 0x3d, 0x3f, 0x82, 0x6c, 0xe4, 0x54, 0xda, 0xce, 0x8e, 0x0b,
	0xee, 0x9c, 0xb7, 0x9b, 0x71, 0xf8, 0x0c, 0x60, 0x9b, 0x21, 0xc9, 0x6b, 0x97, 0x57, 0xda, 0x45,
	0x87, 0xb8, 0x71, 0xe9, 0x6f, 0x9a, 0x32, 0x1f, 0xf7, 0x1f, 0x0e, 0xb7, 0xc1, 0x4c, 0x52, 0x26,
	0x86, 0xe6, 0xad, 0x1d, 0xbc, 0x27, 0x62, 0xb5, 0x26, 0x75, 0x6f, 0x1d, 0x43, 0x6d, 0x7b, 0x34,
	0x19, 0x09, 0x2e, 0xe9, 0xc9, 0x07, 0x78, 0xf2, 0x20, 0x0f, 0x5c, 0x05, 0xf0, 0x6e, 0xfa, 0xe7,
	0xee, 0xc5, 0xe5, 0x4d, 0xe7, 0xac, 0x96, 0xc3, 0x15, 0x28, 0xf6, 0xbc, 0xab, 0x9e, 0xd7, 0xf1,
	0x6a, 0x08, 0x97, 0x61, 0xef, 0xb4, 0xd7, 0xf3, 0xae, 0x6b, 0x79, 0x5c, 0x02, 0xb3, 0xdb, 0xeb,
	0x9e, 0xd7, 0x8c, 0xd3, 0xcf, 0x3f, 0x97, 0x16, 0xba, 0x5f, 0x5a, 0xe8, 0xcf, 0xd2, 0x42, 0xdf,
	0x57, 0x56, 0xee, 0x7e, 0x65, 0xe5, 0x7e, 0xaf, 0xac, 0xdc, 0x97, 0xd6, 0x98, 0xa9, 0xc9, 0x7c,
	0xd0, 0x18, 0x8a, 0xb0, 0x29, 0x64, 0x28, 0x24, 0x93, 0xaf, 0xa7, 0xc1, 0x40, 0x36, 0xf5, 0x43,
	0xb8, 0x1d, 0x37, 0x83, 0x88, 0x3d, 0x7c, 0x0a, 0x83, 0x82, 0xfe, 0x6d, 0xdf, 0xfc, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x49, 0xa6, 0x71, 0x34, 0x2c, 0x03, 0x00, 0x00,
}

func (m *GetPoolsRequestFilter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPoolsRequestFilter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetPoolsRequestFilter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Search) > 0 {
		i -= len(m.Search)
		copy(dAtA[i:], m.Search)
		i = encodeVarintPools(dAtA, i, uint64(len(m.Search)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Denom) > 0 {
		for iNdEx := len(m.Denom) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Denom[iNdEx])
			copy(dAtA[i:], m.Denom[iNdEx])
			i = encodeVarintPools(dAtA, i, uint64(len(m.Denom[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.WithMarketIncentives {
		i--
		if m.WithMarketIncentives {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.MinLiquidityCap != 0 {
		i = encodeVarintPools(dAtA, i, uint64(m.MinLiquidityCap))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Incentive) > 0 {
		dAtA2 := make([]byte, len(m.Incentive)*10)
		var j1 int
		for _, num := range m.Incentive {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintPools(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Type) > 0 {
		dAtA4 := make([]byte, len(m.Type)*10)
		var j3 int
		for _, num := range m.Type {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintPools(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PoolIdNotIn) > 0 {
		dAtA6 := make([]byte, len(m.PoolIdNotIn)*10)
		var j5 int
		for _, num := range m.PoolIdNotIn {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		i -= j5
		copy(dAtA[i:], dAtA6[:j5])
		i = encodeVarintPools(dAtA, i, uint64(j5))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolId) > 0 {
		dAtA8 := make([]byte, len(m.PoolId)*10)
		var j7 int
		for _, num := range m.PoolId {
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintPools(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetPoolsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPoolsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetPoolsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sort != nil {
		{
			size, err := m.Sort.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Filter != nil {
		{
			size, err := m.Filter.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetPoolsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPoolsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetPoolsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintPools(dAtA []byte, offset int, v uint64) int {
	offset -= sovPools(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetPoolsRequestFilter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PoolId) > 0 {
		l = 0
		for _, e := range m.PoolId {
			l += sovPools(uint64(e))
		}
		n += 1 + sovPools(uint64(l)) + l
	}
	if len(m.PoolIdNotIn) > 0 {
		l = 0
		for _, e := range m.PoolIdNotIn {
			l += sovPools(uint64(e))
		}
		n += 1 + sovPools(uint64(l)) + l
	}
	if len(m.Type) > 0 {
		l = 0
		for _, e := range m.Type {
			l += sovPools(uint64(e))
		}
		n += 1 + sovPools(uint64(l)) + l
	}
	if len(m.Incentive) > 0 {
		l = 0
		for _, e := range m.Incentive {
			l += sovPools(uint64(e))
		}
		n += 1 + sovPools(uint64(l)) + l
	}
	if m.MinLiquidityCap != 0 {
		n += 1 + sovPools(uint64(m.MinLiquidityCap))
	}
	if m.WithMarketIncentives {
		n += 2
	}
	if len(m.Denom) > 0 {
		for _, s := range m.Denom {
			l = len(s)
			n += 1 + l + sovPools(uint64(l))
		}
	}
	l = len(m.Search)
	if l > 0 {
		n += 1 + l + sovPools(uint64(l))
	}
	return n
}

func (m *GetPoolsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Filter != nil {
		l = m.Filter.Size()
		n += 1 + l + sovPools(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovPools(uint64(l))
	}
	if m.Sort != nil {
		l = m.Sort.Size()
		n += 1 + l + sovPools(uint64(l))
	}
	return n
}

func (m *GetPoolsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovPools(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPools(x uint64) (n int) {
	return sovPools(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetPoolsRequestFilter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPoolsRequestFilter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPoolsRequestFilter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.PoolId = append(m.PoolId, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPools
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPools
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.PoolId) == 0 {
					m.PoolId = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPools
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.PoolId = append(m.PoolId, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.PoolIdNotIn = append(m.PoolIdNotIn, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPools
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPools
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.PoolIdNotIn) == 0 {
					m.PoolIdNotIn = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPools
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.PoolIdNotIn = append(m.PoolIdNotIn, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolIdNotIn", wireType)
			}
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Type = append(m.Type, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPools
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPools
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Type) == 0 {
					m.Type = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPools
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Type = append(m.Type, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
		case 4:
			if wireType == 0 {
				var v IncentiveType
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= IncentiveType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Incentive = append(m.Incentive, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPools
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPools
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Incentive) == 0 {
					m.Incentive = make([]IncentiveType, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v IncentiveType
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPools
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= IncentiveType(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Incentive = append(m.Incentive, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Incentive", wireType)
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLiquidityCap", wireType)
			}
			m.MinLiquidityCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLiquidityCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithMarketIncentives", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithMarketIncentives = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPools
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = append(m.Denom, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Search", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPools
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Search = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetPoolsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPoolsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPoolsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Filter == nil {
				m.Filter = &GetPoolsRequestFilter{}
			}
			if err := m.Filter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &v1beta1.PaginationRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sort", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sort == nil {
				m.Sort = &v1beta1.SortRequest{}
			}
			if err := m.Sort.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetPoolsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPoolsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPoolsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPools(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPools
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPools
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPools
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPools
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPools        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPools          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPools = fmt.Errorf("proto: unexpected end of group")
)
