// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqs/pools/v1beta1/pools.proto

package pools

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	v1beta1 "github.com/osmosis-labs/sqs/pkg/api/v1beta1"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GetPoolsRequest is the request type for the Service.Get RPC method.
type GetPoolsRequest struct {
	// pool_id is the pool id to query. If not provided, will return all pools.
	PoolId []uint64 `protobuf:"varint,1,rep,packed,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// min_liquidity_cap is the minimum liquidity cap to filter pools by.
	MinLiquidityCap uint64 `protobuf:"varint,2,opt,name=min_liquidity_cap,json=minLiquidityCap,proto3" json:"min_liquidity_cap,omitempty"`
	// with_market_incentives indicates whether to include incentives into pools
	// response.
	WithMarketIncentives bool `protobuf:"varint,3,opt,name=with_market_incentives,json=withMarketIncentives,proto3" json:"with_market_incentives,omitempty"`
	// Pagination options for the result set
	Pagination *v1beta1.PaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Sort options for the result set
	Sort *v1beta1.SortRequest `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (m *GetPoolsRequest) Reset()         { *m = GetPoolsRequest{} }
func (m *GetPoolsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPoolsRequest) ProtoMessage()    {}
func (*GetPoolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30f2696e6c186971, []int{0}
}
func (m *GetPoolsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPoolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPoolsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetPoolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolsRequest.Merge(m, src)
}
func (m *GetPoolsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetPoolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolsRequest proto.InternalMessageInfo

func (m *GetPoolsRequest) GetPoolId() []uint64 {
	if m != nil {
		return m.PoolId
	}
	return nil
}

func (m *GetPoolsRequest) GetMinLiquidityCap() uint64 {
	if m != nil {
		return m.MinLiquidityCap
	}
	return 0
}

func (m *GetPoolsRequest) GetWithMarketIncentives() bool {
	if m != nil {
		return m.WithMarketIncentives
	}
	return false
}

func (m *GetPoolsRequest) GetPagination() *v1beta1.PaginationRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetPoolsRequest) GetSort() *v1beta1.SortRequest {
	if m != nil {
		return m.Sort
	}
	return nil
}

// TODO: Add more fields to the response
type GetPoolsResponse struct {
}

func (m *GetPoolsResponse) Reset()         { *m = GetPoolsResponse{} }
func (m *GetPoolsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPoolsResponse) ProtoMessage()    {}
func (*GetPoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30f2696e6c186971, []int{1}
}
func (m *GetPoolsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPoolsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetPoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolsResponse.Merge(m, src)
}
func (m *GetPoolsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetPoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetPoolsRequest)(nil), "sqs.pools.v1beta1.GetPoolsRequest")
	proto.RegisterType((*GetPoolsResponse)(nil), "sqs.pools.v1beta1.GetPoolsResponse")
}

func init() { proto.RegisterFile("sqs/pools/v1beta1/pools.proto", fileDescriptor_30f2696e6c186971) }

var fileDescriptor_30f2696e6c186971 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0x36, 0x6f, 0x5f, 0x59, 0x0f, 0xb5, 0x41, 0x34, 0x14, 0x5d, 0x42, 0xf1, 0x10,
	0x04, 0x13, 0x5a, 0xfd, 0x04, 0x2a, 0x48, 0x51, 0xa1, 0xc4, 0x9b, 0x97, 0xb0, 0x69, 0x97, 0x76,
	0x68, 0xb3, 0x9b, 0x64, 0x36, 0x95, 0x7e, 0x01, 0xcf, 0x7e, 0x2c, 0x8f, 0x3d, 0x7a, 0x94, 0xf6,
	0x8b, 0xc8, 0x26, 0xfd, 0xa3, 0xe8, 0x71, 0xe6, 0x79, 0x7e, 0xbb, 0xf3, 0xcc, 0x90, 0x53, 0x4c,
	0xd1, 0x4f, 0xa4, 0x9c, 0xa2, 0x3f, 0xeb, 0x44, 0x5c, 0xb1, 0x4e, 0x59, 0x79, 0x49, 0x26, 0x95,
	0xb4, 0x9a, 0x98, 0xa2, 0x57, 0x36, 0xd6, 0x72, 0xab, 0xad, 0x89, 0x34, 0xe7, 0xd9, 0x7c, 0x47,
	0xb0, 0x11, 0x08, 0xa6, 0x40, 0x8a, 0x12, 0x6b, 0x9d, 0xfc, 0xf6, 0xa0, 0xcc, 0x54, 0xa9, 0xb6,
	0x5f, 0xab, 0xa4, 0x71, 0xc7, 0x55, 0x5f, 0x3f, 0x1b, 0xf0, 0x34, 0xe7, 0xa8, 0xac, 0x63, 0xf2,
	0x5f, 0x7f, 0x13, 0xc2, 0xd0, 0x36, 0x9c, 0x9a, 0x6b, 0x06, 0x75, 0x5d, 0xf6, 0x86, 0xd6, 0x39,
	0x69, 0xc6, 0x20, 0xc2, 0x29, 0xa4, 0x39, 0x0c, 0x41, 0xcd, 0xc3, 0x01, 0x4b, 0xec, 0xaa, 0x63,
	0xb8, 0x66, 0xd0, 0x88, 0x41, 0x3c, 0x6c, 0xfa, 0x37, 0x2c, 0xb1, 0xae, 0xc8, 0xd1, 0x0b, 0xa8,
	0x71, 0x18, 0xb3, 0x6c, 0xc2, 0x55, 0x08, 0x62, 0xc0, 0x85, 0x82, 0x19, 0x47, 0xbb, 0xe6, 0x18,
	0xee, 0x5e, 0x70, 0xa8, 0xd5, 0xc7, 0x42, 0xec, 0x6d, 0x35, 0xeb, 0x96, 0x90, 0x5d, 0x00, 0xdb,
	0x74, 0x0c, 0x77, 0xbf, 0x7b, 0xe6, 0xe9, 0xe0, 0x45, 0x82, 0x4d, 0x70, 0xaf, 0xbf, 0x35, 0xad,
	0x87, 0x0e, 0xbe, 0x71, 0x56, 0x97, 0x98, 0x3a, 0xa2, 0xfd, 0xaf, 0xe0, 0xe9, 0x1f, 0xfc, 0x93,
	0xcc, 0xd4, 0x86, 0x2c, 0xbc, 0x6d, 0x8b, 0x1c, 0xec, 0xf6, 0x80, 0x89, 0x14, 0xc8, 0xaf, 0xef,
	0xdf, 0x97, 0xd4, 0x58, 0x2c, 0xa9, 0xf1, 0xb9, 0xa4, 0xc6, 0xdb, 0x8a, 0x56, 0x16, 0x2b, 0x5a,
	0xf9, 0x58, 0xd1, 0xca, 0x73, 0x67, 0x04, 0x6a, 0x9c, 0x47, 0xde, 0x40, 0xc6, 0xbe, 0xc4, 0x58,
	0x22, 0xe0, 0xc5, 0x94, 0x45, 0xe8, 0x17, 0x27, 0x9c, 0x8c, 0x7c, 0x96, 0xc0, 0xcf, 0x23, 0x46,
	0xf5, 0x62, 0xe1, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0x77, 0x0a, 0x84, 0xe6, 0x01,
	0x00, 0x00,
}

func (m *GetPoolsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPoolsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetPoolsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sort != nil {
		{
			size, err := m.Sort.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.WithMarketIncentives {
		i--
		if m.WithMarketIncentives {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MinLiquidityCap != 0 {
		i = encodeVarintPools(dAtA, i, uint64(m.MinLiquidityCap))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PoolId) > 0 {
		dAtA4 := make([]byte, len(m.PoolId)*10)
		var j3 int
		for _, num := range m.PoolId {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintPools(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetPoolsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPoolsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetPoolsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintPools(dAtA []byte, offset int, v uint64) int {
	offset -= sovPools(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetPoolsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PoolId) > 0 {
		l = 0
		for _, e := range m.PoolId {
			l += sovPools(uint64(e))
		}
		n += 1 + sovPools(uint64(l)) + l
	}
	if m.MinLiquidityCap != 0 {
		n += 1 + sovPools(uint64(m.MinLiquidityCap))
	}
	if m.WithMarketIncentives {
		n += 2
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovPools(uint64(l))
	}
	if m.Sort != nil {
		l = m.Sort.Size()
		n += 1 + l + sovPools(uint64(l))
	}
	return n
}

func (m *GetPoolsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovPools(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPools(x uint64) (n int) {
	return sovPools(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetPoolsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPoolsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPoolsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.PoolId = append(m.PoolId, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPools
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPools
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.PoolId) == 0 {
					m.PoolId = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPools
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.PoolId = append(m.PoolId, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLiquidityCap", wireType)
			}
			m.MinLiquidityCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLiquidityCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithMarketIncentives", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithMarketIncentives = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &v1beta1.PaginationRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sort", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sort == nil {
				m.Sort = &v1beta1.SortRequest{}
			}
			if err := m.Sort.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetPoolsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPoolsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPoolsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPools(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPools
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPools
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPools
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPools
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPools        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPools          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPools = fmt.Errorf("proto: unexpected end of group")
)
