// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqs/pools/v1beta1/query.proto

package pools

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/osmosis-labs/sqs/pkg/api/v1beta1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("sqs/pools/v1beta1/query.proto", fileDescriptor_05711caafa6f54ad) }

var fileDescriptor_05711caafa6f54ad = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0x5b, 0xe1, 0x3d, 0xa4, 0x83, 0x60, 0xc7, 0xf2, 0xcc, 0x50, 0x67, 0x13, 0xaa, 0xff,
	0xc0, 0xc5, 0xc1, 0x45, 0x1d, 0x9d, 0x4c, 0x24, 0xc4, 0x60, 0x5f, 0x6e, 0xd2, 0x7b, 0x2b, 0xb8,
	0xfa, 0x0b, 0x04, 0xff, 0x94, 0xe3, 0x03, 0x17, 0x47, 0x69, 0xfd, 0x21, 0xd2, 0xe4, 0x81, 0x48,
	0xe5, 0xcd, 0xdf, 0x39, 0xe7, 0x9e, 0x73, 0x8b, 0x23, 0x0c, 0x28, 0x3c, 0x40, 0x8b, 0xe2, 0xa9,
	0x51, 0x9a, 0x64, 0x23, 0x42, 0xaf, 0xbb, 0x67, 0xee, 0x3b, 0x20, 0x28, 0x0f, 0x31, 0x20, 0x8f,
	0x98, 0x6f, 0x71, 0xb5, 0x32, 0x00, 0xa6, 0xd5, 0x42, 0x7a, 0x2b, 0xa4, 0x73, 0x40, 0x92, 0x2c,
	0x38, 0x4c, 0x86, 0xea, 0x9f, 0xbc, 0x64, 0x4f, 0xb8, 0x9e, 0x70, 0x3c, 0xf0, 0x8b, 0xa5, 0xb1,
	0x2e, 0x66, 0x6c, 0x35, 0xab, 0xb9, 0x06, 0xa1, 0xa3, 0x44, 0x4f, 0x6d, 0xb1, 0xb8, 0x9e, 0x58,
	0x79, 0x57, 0x2c, 0xae, 0xa6, 0xe4, 0xb2, 0xe6, 0xb3, 0x92, 0xfc, 0x42, 0x53, 0x84, 0x37, 0x3a,
	0xf4, 0x1a, 0xa9, 0x3a, 0xde, 0xa9, 0x41, 0x0f, 0x0e, 0x75, 0x7d, 0xf0, 0xf2, 0xf1, 0xfd, 0xb6,
	0xb7, 0x5f, 0x2e, 0x53, 0xe5, 0xf3, 0xcb, 0xf7, 0x81, 0xe5, 0x9b, 0x81, 0xe5, 0x5f, 0x03, 0xcb,
	0x5f, 0x47, 0x96, 0x6d, 0x46, 0x96, 0x7d, 0x8e, 0x2c, 0xbb, 0x6d, 0x8c, 0xa5, 0x87, 0x5e, 0xf1,
	0x7b, 0x58, 0x0b, 0xc0, 0x35, 0xa0, 0xc5, 0x93, 0x56, 0x2a, 0x14, 0x71, 0xfd, 0xa3, 0x89, 0xcf,
	0xf9, 0xb3, 0x5f, 0x2d, 0x63, 0xfd, 0xb3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0xb3, 0x8e,
	0x29, 0x71, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Pools returns all the existing pools.
	Pools(ctx context.Context, in *GetPoolsRequest, opts ...grpc.CallOption) (*GetPoolsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Pools(ctx context.Context, in *GetPoolsRequest, opts ...grpc.CallOption) (*GetPoolsResponse, error) {
	out := new(GetPoolsResponse)
	err := c.cc.Invoke(ctx, "/sqs.pools.v1beta1.Query/Pools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Pools returns all the existing pools.
	Pools(context.Context, *GetPoolsRequest) (*GetPoolsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Pools(ctx context.Context, req *GetPoolsRequest) (*GetPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pools not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Pools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Pools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sqs.pools.v1beta1.Query/Pools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Pools(ctx, req.(*GetPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sqs.pools.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pools",
			Handler:    _Query_Pools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sqs/pools/v1beta1/query.proto",
}
