// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/osmosis-labs/osmosis/v19/x/poolmanager/types"
	mock "github.com/stretchr/testify/mock"
)

// CosmWasmPoolI is an autogenerated mock type for the CosmWasmPoolI type
type CosmWasmPoolI struct {
	mock.Mock
}

type CosmWasmPoolI_Expecter struct {
	mock *mock.Mock
}

func (_m *CosmWasmPoolI) EXPECT() *CosmWasmPoolI_Expecter {
	return &CosmWasmPoolI_Expecter{mock: &_m.Mock}
}

// GetId provides a mock function with given fields:
func (_m *CosmWasmPoolI) GetId() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// CosmWasmPoolI_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type CosmWasmPoolI_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *CosmWasmPoolI_Expecter) GetId() *CosmWasmPoolI_GetId_Call {
	return &CosmWasmPoolI_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *CosmWasmPoolI_GetId_Call) Run(run func()) *CosmWasmPoolI_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CosmWasmPoolI_GetId_Call) Return(_a0 uint64) *CosmWasmPoolI_GetId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CosmWasmPoolI_GetId_Call) RunAndReturn(run func() uint64) *CosmWasmPoolI_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function with given fields:
func (_m *CosmWasmPoolI) GetType() types.PoolType {
	ret := _m.Called()

	var r0 types.PoolType
	if rf, ok := ret.Get(0).(func() types.PoolType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.PoolType)
	}

	return r0
}

// CosmWasmPoolI_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type CosmWasmPoolI_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *CosmWasmPoolI_Expecter) GetType() *CosmWasmPoolI_GetType_Call {
	return &CosmWasmPoolI_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *CosmWasmPoolI_GetType_Call) Run(run func()) *CosmWasmPoolI_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CosmWasmPoolI_GetType_Call) Return(_a0 types.PoolType) *CosmWasmPoolI_GetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CosmWasmPoolI_GetType_Call) RunAndReturn(run func() types.PoolType) *CosmWasmPoolI_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// NewCosmWasmPoolI creates a new instance of CosmWasmPoolI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCosmWasmPoolI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CosmWasmPoolI {
	mock := &CosmWasmPoolI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
