// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/osmosis-labs/osmosis/v20/x/poolmanager/types"
	mock "github.com/stretchr/testify/mock"
)

// PoolI is an autogenerated mock type for the PoolI type
type PoolI struct {
	mock.Mock
}

type PoolI_Expecter struct {
	mock *mock.Mock
}

func (_m *PoolI) EXPECT() *PoolI_Expecter {
	return &PoolI_Expecter{mock: &_m.Mock}
}

// GetId provides a mock function with given fields:
func (_m *PoolI) GetId() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// PoolI_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type PoolI_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *PoolI_Expecter) GetId() *PoolI_GetId_Call {
	return &PoolI_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *PoolI_GetId_Call) Run(run func()) *PoolI_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PoolI_GetId_Call) Return(_a0 uint64) *PoolI_GetId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PoolI_GetId_Call) RunAndReturn(run func() uint64) *PoolI_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function with given fields:
func (_m *PoolI) GetType() types.PoolType {
	ret := _m.Called()

	var r0 types.PoolType
	if rf, ok := ret.Get(0).(func() types.PoolType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.PoolType)
	}

	return r0
}

// PoolI_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type PoolI_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *PoolI_Expecter) GetType() *PoolI_GetType_Call {
	return &PoolI_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *PoolI_GetType_Call) Run(run func()) *PoolI_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PoolI_GetType_Call) Return(_a0 types.PoolType) *PoolI_GetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PoolI_GetType_Call) RunAndReturn(run func() types.PoolType) *PoolI_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// NewPoolI creates a new instance of PoolI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPoolI(t interface {
	mock.TestingT
	Cleanup(func())
}) *PoolI {
	mock := &PoolI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
