defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: automerge to the base branch with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>=1"
      - base=v21.x
      - label=A:automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
  - name: backport patches to osmosis-main branch
    conditions:
      - base=v21.x
      - label=A:backport/osmosis-main
    actions:
      backport:
        branches:
          - osmosis-main
  - name: backport patches to v22.x branch
    conditions:
      - base=v21.x
      - label=A:backport/v22.x
    actions:
      backport:
        branches:
          - v22.x
  - name: backport patches to v23.x branch
    conditions:
      - base=v21.x
      - label=A:backport/v23.x
    actions:
      backport:
        branches:
          - v23.x
