defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - base=v21.x
      - label=A:automerge
    merge_conditions:
      - "#approved-reviews-by>=1"
    commit_message_format:
      title: pr-title
      body: pr-body
    merge_method: squash

pull_request_rules:
  - name: backport patches to osmosis-main branch
    conditions:
      - base=v22.x
      - label=A:backport/osmosis-main
    actions:
      backport:
        branches:
          - osmosis-main
  - name: backport patches to v21.x branch
    conditions:
      - base=v22.x
      - label=A:backport/v21.x
    actions:
      backport:
        branches:
          - v21.x
  - name: backport patches to v23.x branch
    conditions:
      - base=v22.x
      - label=A:backport/v23.x
    actions:
      backport:
        branches:
          - v23.x
  - name: backport patches to v24.x branch
    conditions:
      - base=v23.x
      - label=A:backport/v24.x
    actions:
      backport:
        branches:
          - v24.x
  - name: backport patches to v25.x branch
    conditions:
      - base=v24.x
      - label=A:backport/v25.x
    actions:
      backport:
        branches:
          - v25.x
  - name: automerge to the base branch with label automerge and branch protection passing
    conditions: []
    actions:
      queue:
