// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: ingest.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PoolData represents a structure encapsulating an Osmosis liquidity pool.
type PoolData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ChainModel is the chain representation model of the pool.
	ChainModel []byte `protobuf:"bytes,1,opt,name=chain_model,json=chainModel,proto3" json:"chain_model,omitempty"`
	// SqsModel is additional pool data used by the sidecar query server.
	SqsModel []byte `protobuf:"bytes,2,opt,name=sqs_model,json=sqsModel,proto3" json:"sqs_model,omitempty"`
	// TickModel is the tick data of a concentrated liquidity pool.
	// This field is only valid and set for concentrated pools. It is nil otherwise.
	TickModel []byte `protobuf:"bytes,3,opt,name=tick_model,json=tickModel,proto3" json:"tick_model,omitempty"`
}

func (x *PoolData) Reset() {
	*x = PoolData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolData) ProtoMessage() {}

func (x *PoolData) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolData.ProtoReflect.Descriptor instead.
func (*PoolData) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *PoolData) GetChainModel() []byte {
	if x != nil {
		return x.ChainModel
	}
	return nil
}

func (x *PoolData) GetSqsModel() []byte {
	if x != nil {
		return x.SqsModel
	}
	return nil
}

func (x *PoolData) GetTickModel() []byte {
	if x != nil {
		return x.TickModel
	}
	return nil
}

// The pools data chunks streamed by the client.
type ChainPoolsDataChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pools []*PoolData `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
}

func (x *ChainPoolsDataChunk) Reset() {
	*x = ChainPoolsDataChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainPoolsDataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainPoolsDataChunk) ProtoMessage() {}

func (x *ChainPoolsDataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainPoolsDataChunk.ProtoReflect.Descriptor instead.
func (*ChainPoolsDataChunk) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *ChainPoolsDataChunk) GetPools() []*PoolData {
	if x != nil {
		return x.Pools
	}
	return nil
}

// The response after completing pools client-streaming.
type ProcessChainPoolsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessChainPoolsReply) Reset() {
	*x = ProcessChainPoolsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessChainPoolsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessChainPoolsReply) ProtoMessage() {}

func (x *ProcessChainPoolsReply) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessChainPoolsReply.ProtoReflect.Descriptor instead.
func (*ProcessChainPoolsReply) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{2}
}

// The start block process request.
// Sends taker fees and block height.
type StartBlockProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// block height is the height of the block being processed.
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// taker_fees_map is the map of taker fees for the block.
	TakerFeesMap []byte `protobuf:"bytes,2,opt,name=taker_fees_map,json=takerFeesMap,proto3" json:"taker_fees_map,omitempty"`
}

func (x *StartBlockProcessRequest) Reset() {
	*x = StartBlockProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBlockProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBlockProcessRequest) ProtoMessage() {}

func (x *StartBlockProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBlockProcessRequest.ProtoReflect.Descriptor instead.
func (*StartBlockProcessRequest) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *StartBlockProcessRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *StartBlockProcessRequest) GetTakerFeesMap() []byte {
	if x != nil {
		return x.TakerFeesMap
	}
	return nil
}

// The response after completing start block processing.
type StartBlockProcessReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartBlockProcessReply) Reset() {
	*x = StartBlockProcessReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBlockProcessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBlockProcessReply) ProtoMessage() {}

func (x *StartBlockProcessReply) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBlockProcessReply.ProtoReflect.Descriptor instead.
func (*StartBlockProcessReply) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{4}
}

// The request to end the block processing.
type EndBlockProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (x *EndBlockProcessRequest) Reset() {
	*x = EndBlockProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndBlockProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndBlockProcessRequest) ProtoMessage() {}

func (x *EndBlockProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndBlockProcessRequest.ProtoReflect.Descriptor instead.
func (*EndBlockProcessRequest) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *EndBlockProcessRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// The response to end the block processing.
type EndBlockProcessReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndBlockProcessReply) Reset() {
	*x = EndBlockProcessReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingest_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndBlockProcessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndBlockProcessReply) ProtoMessage() {}

func (x *EndBlockProcessReply) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndBlockProcessReply.ProtoReflect.Descriptor instead.
func (*EndBlockProcessReply) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{6}
}

var File_ingest_proto protoreflect.FileDescriptor

var file_ingest_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x73, 0x71, 0x73, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x22, 0x67, 0x0a, 0x08, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x71, 0x73, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x73, 0x71, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x69, 0x63, 0x6b, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x49, 0x0a, 0x13, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x12, 0x32, 0x0a, 0x05, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x71, 0x73, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x05, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x63, 0x0a, 0x18, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x24, 0x0a, 0x0e, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x66, 0x65, 0x65, 0x73, 0x5f, 0x6d, 0x61,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x46, 0x65,
	0x65, 0x73, 0x4d, 0x61, 0x70, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x3b, 0x0a, 0x16, 0x45, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x16, 0x0a, 0x14,
	0x45, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0xd7, 0x02, 0x0a, 0x0b, 0x53, 0x51, 0x53, 0x49, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x6f, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x2e, 0x73, 0x71, 0x73, 0x2e,
	0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x71, 0x73, 0x2e, 0x69, 0x6e,
	0x67, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x27, 0x2e, 0x73, 0x71, 0x73,
	0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x1a, 0x2a, 0x2e, 0x73, 0x71, 0x73, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x28, 0x01, 0x12, 0x69, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2a, 0x2e, 0x73, 0x71, 0x73, 0x2e, 0x69, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x45, 0x6e, 0x64, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x73, 0x71, 0x73, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x45, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x17,
	0x5a, 0x15, 0x73, 0x71, 0x73, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ingest_proto_rawDescOnce sync.Once
	file_ingest_proto_rawDescData = file_ingest_proto_rawDesc
)

func file_ingest_proto_rawDescGZIP() []byte {
	file_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(file_ingest_proto_rawDescData)
	})
	return file_ingest_proto_rawDescData
}

var file_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ingest_proto_goTypes = []interface{}{
	(*PoolData)(nil),                 // 0: sqs.ingest.v1beta1.PoolData
	(*ChainPoolsDataChunk)(nil),      // 1: sqs.ingest.v1beta1.ChainPoolsDataChunk
	(*ProcessChainPoolsReply)(nil),   // 2: sqs.ingest.v1beta1.ProcessChainPoolsReply
	(*StartBlockProcessRequest)(nil), // 3: sqs.ingest.v1beta1.StartBlockProcessRequest
	(*StartBlockProcessReply)(nil),   // 4: sqs.ingest.v1beta1.StartBlockProcessReply
	(*EndBlockProcessRequest)(nil),   // 5: sqs.ingest.v1beta1.EndBlockProcessRequest
	(*EndBlockProcessReply)(nil),     // 6: sqs.ingest.v1beta1.EndBlockProcessReply
}
var file_ingest_proto_depIdxs = []int32{
	0, // 0: sqs.ingest.v1beta1.ChainPoolsDataChunk.pools:type_name -> sqs.ingest.v1beta1.PoolData
	3, // 1: sqs.ingest.v1beta1.SQSIngester.StartBlockProcess:input_type -> sqs.ingest.v1beta1.StartBlockProcessRequest
	1, // 2: sqs.ingest.v1beta1.SQSIngester.ProcessChainPools:input_type -> sqs.ingest.v1beta1.ChainPoolsDataChunk
	5, // 3: sqs.ingest.v1beta1.SQSIngester.EndBlockProcess:input_type -> sqs.ingest.v1beta1.EndBlockProcessRequest
	4, // 4: sqs.ingest.v1beta1.SQSIngester.StartBlockProcess:output_type -> sqs.ingest.v1beta1.StartBlockProcessReply
	2, // 5: sqs.ingest.v1beta1.SQSIngester.ProcessChainPools:output_type -> sqs.ingest.v1beta1.ProcessChainPoolsReply
	6, // 6: sqs.ingest.v1beta1.SQSIngester.EndBlockProcess:output_type -> sqs.ingest.v1beta1.EndBlockProcessReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ingest_proto_init() }
func file_ingest_proto_init() {
	if File_ingest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ingest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainPoolsDataChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessChainPoolsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBlockProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBlockProcessReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingest_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndBlockProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingest_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndBlockProcessReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ingest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_proto_depIdxs,
		MessageInfos:      file_ingest_proto_msgTypes,
	}.Build()
	File_ingest_proto = out.File
	file_ingest_proto_rawDesc = nil
	file_ingest_proto_goTypes = nil
	file_ingest_proto_depIdxs = nil
}
