// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqs/query/v1beta1/sort.proto

package v1beta1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SortDirection represents the direction for sorting.
type SortDirection int32

const (
	SortDirection_ASCENDING  SortDirection = 0
	SortDirection_DESCENDING SortDirection = 1
)

var SortDirection_name = map[int32]string{
	0: "ASCENDING",
	1: "DESCENDING",
}

var SortDirection_value = map[string]int32{
	"ASCENDING":  0,
	"DESCENDING": 1,
}

func (x SortDirection) String() string {
	return proto.EnumName(SortDirection_name, int32(x))
}

func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2084d9d808812ac7, []int{0}
}

// SortField represents a field to sort by, including its direction.
type SortField struct {
	Field     string        `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction SortDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=sqs.query.v1beta1.SortDirection" json:"direction,omitempty"`
}

func (m *SortField) Reset()         { *m = SortField{} }
func (m *SortField) String() string { return proto.CompactTextString(m) }
func (*SortField) ProtoMessage()    {}
func (*SortField) Descriptor() ([]byte, []int) {
	return fileDescriptor_2084d9d808812ac7, []int{0}
}
func (m *SortField) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SortField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SortField.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SortField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortField.Merge(m, src)
}
func (m *SortField) XXX_Size() int {
	return m.Size()
}
func (m *SortField) XXX_DiscardUnknown() {
	xxx_messageInfo_SortField.DiscardUnknown(m)
}

var xxx_messageInfo_SortField proto.InternalMessageInfo

func (m *SortField) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *SortField) GetDirection() SortDirection {
	if m != nil {
		return m.Direction
	}
	return SortDirection_ASCENDING
}

// Sort represents multiple sort fields.
type SortRequest struct {
	Fields []*SortField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (m *SortRequest) Reset()         { *m = SortRequest{} }
func (m *SortRequest) String() string { return proto.CompactTextString(m) }
func (*SortRequest) ProtoMessage()    {}
func (*SortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2084d9d808812ac7, []int{1}
}
func (m *SortRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SortRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortRequest.Merge(m, src)
}
func (m *SortRequest) XXX_Size() int {
	return m.Size()
}
func (m *SortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SortRequest proto.InternalMessageInfo

func (m *SortRequest) GetFields() []*SortField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterEnum("sqs.query.v1beta1.SortDirection", SortDirection_name, SortDirection_value)
	proto.RegisterType((*SortField)(nil), "sqs.query.v1beta1.SortField")
	proto.RegisterType((*SortRequest)(nil), "sqs.query.v1beta1.SortRequest")
}

func init() { proto.RegisterFile("sqs/query/v1beta1/sort.proto", fileDescriptor_2084d9d808812ac7) }

var fileDescriptor_2084d9d808812ac7 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x6a, 0x2a, 0x31,
	0x14, 0x86, 0x27, 0xf7, 0x72, 0x85, 0x89, 0x28, 0xd7, 0x41, 0xb8, 0x22, 0x12, 0x06, 0x57, 0x72,
	0x4b, 0x13, 0xb4, 0x5d, 0x17, 0x5a, 0xb5, 0xa5, 0x1b, 0x17, 0xe3, 0xae, 0xbb, 0xcc, 0x18, 0xd3,
	0x50, 0xc7, 0xe3, 0x4c, 0x32, 0x42, 0xdf, 0xa2, 0x8f, 0xd5, 0xa5, 0xcb, 0x2e, 0x8b, 0xbe, 0x48,
	0x49, 0x9c, 0xb1, 0x94, 0xd2, 0xcd, 0xcc, 0x39, 0xf9, 0x4e, 0xfe, 0x3f, 0xf9, 0x83, 0x7b, 0x3a,
	0xd3, 0x2c, 0x2b, 0x44, 0xfe, 0xcc, 0xb6, 0xc3, 0x58, 0x18, 0x3e, 0x64, 0x1a, 0x72, 0x43, 0x37,
	0x39, 0x18, 0x08, 0x5a, 0x3a, 0xd3, 0xd4, 0x51, 0x5a, 0xd2, 0x6e, 0x5b, 0x82, 0x04, 0x47, 0x99,
	0xad, 0x8e, 0x83, 0xdd, 0x16, 0x4f, 0xd5, 0x1a, 0x98, 0xfb, 0x96, 0x4b, 0x44, 0x02, 0xc8, 0x95,
	0x60, 0xae, 0x8b, 0x8b, 0x25, 0x5b, 0x14, 0x39, 0x37, 0x0a, 0xd6, 0x15, 0x4f, 0x40, 0xa7, 0xa0,
	0x59, 0xcc, 0xb5, 0x38, 0x79, 0x27, 0xa0, 0x2a, 0xfe, 0xaf, 0xe4, 0xa9, 0x96, 0x6c, 0x3b, 0xb4,
	0xbf, 0x23, 0xe8, 0x73, 0xec, 0xcf, 0x21, 0x37, 0xb7, 0x4a, 0xac, 0x16, 0x41, 0x1b, 0xff, 0x59,
	0xda, 0xa2, 0x83, 0x42, 0x34, 0xf0, 0xa3, 0x63, 0x13, 0x5c, 0x61, 0x7f, 0xa1, 0x72, 0x91, 0x58,
	0xbb, 0xce, 0xaf, 0x10, 0x0d, 0x9a, 0xa3, 0x90, 0x7e, 0xbb, 0x0b, 0xb5, 0x32, 0x93, 0x6a, 0x2e,
	0xfa, 0xdc, 0xd2, 0x1f, 0xe3, 0xba, 0x65, 0x91, 0xc8, 0x0a, 0xa1, 0x4d, 0x70, 0x89, 0x6b, 0x4e,
	0x57, 0x77, 0x50, 0xf8, 0x7b, 0x50, 0x1f, 0xf5, 0x7e, 0xd0, 0x72, 0x47, 0x8a, 0xca, 0xd9, 0xff,
	0x14, 0x37, 0xbe, 0x18, 0x04, 0x0d, 0xec, 0x5f, 0xcf, 0xc7, 0xd3, 0xd9, 0xe4, 0x7e, 0x76, 0xf7,
	0xd7, 0x0b, 0x9a, 0x18, 0x4f, 0xa6, 0xa7, 0x1e, 0xdd, 0x4c, 0x5f, 0xf7, 0x04, 0xed, 0xf6, 0x04,
	0xbd, 0xef, 0x09, 0x7a, 0x39, 0x10, 0x6f, 0x77, 0x20, 0xde, 0xdb, 0x81, 0x78, 0x0f, 0x67, 0x52,
	0x99, 0xc7, 0x22, 0xa6, 0x09, 0xa4, 0xcc, 0x85, 0xa2, 0xf4, 0xf9, 0x8a, 0xc7, 0x9a, 0xd9, 0xc7,
	0xdb, 0x3c, 0x49, 0xc6, 0x37, 0xaa, 0x8a, 0x30, 0xae, 0xb9, 0x94, 0x2e, 0x3e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x2b, 0x98, 0x14, 0xae, 0xda, 0x01, 0x00, 0x00,
}

func (m *SortField) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SortField) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SortField) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Direction != 0 {
		i = encodeVarintSort(dAtA, i, uint64(m.Direction))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Field) > 0 {
		i -= len(m.Field)
		copy(dAtA[i:], m.Field)
		i = encodeVarintSort(dAtA, i, uint64(len(m.Field)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SortRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SortRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SortRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fields) > 0 {
		for iNdEx := len(m.Fields) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fields[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSort(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintSort(dAtA []byte, offset int, v uint64) int {
	offset -= sovSort(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SortField) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Field)
	if l > 0 {
		n += 1 + l + sovSort(uint64(l))
	}
	if m.Direction != 0 {
		n += 1 + sovSort(uint64(m.Direction))
	}
	return n
}

func (m *SortRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Fields) > 0 {
		for _, e := range m.Fields {
			l = e.Size()
			n += 1 + l + sovSort(uint64(l))
		}
	}
	return n
}

func sovSort(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSort(x uint64) (n int) {
	return sovSort(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SortField) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSort
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SortField: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SortField: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSort
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSort
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSort
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Field = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Direction", wireType)
			}
			m.Direction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSort
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Direction |= SortDirection(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSort(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSort
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SortRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSort
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SortRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SortRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fields", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSort
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSort
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSort
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fields = append(m.Fields, &SortField{})
			if err := m.Fields[len(m.Fields)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSort(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSort
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSort(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSort
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSort
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSort
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSort
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSort
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSort
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSort        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSort          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSort = fmt.Errorf("proto: unexpected end of group")
)
