syntax = "proto3";
package sqs.query.v1beta1;

option go_package = "github.com/osmosis-labs/sqs/pkg/api/v1beta1";

message PaginationRequest {
  // page is the page number to query, starts at 0. If not provided, will
  // default to first page.
  uint64 page = 1;

  // limit is the total number of results to be returned in the result page.
  // If left empty it will default to a value to be set by each app.
  uint64 limit = 2;

  // cursor-based pagination is compatible with and similar to offset
  // pagination. If you have a cursor of 50 and a limit of 20, you will get
  // items 50-69. Client should re-request all data if it changes, as the cursor
  // is not a pointer to a page, but to an item index.
  uint64 cursor = 3;
}
