// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqs/pools/pools.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GetRequest is the request type for the Service.Get RPC method.
type GetPoolsRequest struct {
	PoolId               []uint64 `protobuf:"varint,1,rep,packed,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	MinLiquidityCap      uint64   `protobuf:"varint,2,opt,name=min_liquidity_cap,json=minLiquidityCap,proto3" json:"min_liquidity_cap,omitempty"`
	WithMarketIncentives bool     `protobuf:"varint,3,opt,name=with_market_incentives,json=withMarketIncentives,proto3" json:"with_market_incentives,omitempty"`
}

func (m *GetPoolsRequest) Reset()         { *m = GetPoolsRequest{} }
func (m *GetPoolsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPoolsRequest) ProtoMessage()    {}
func (*GetPoolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a656353c33113850, []int{0}
}
func (m *GetPoolsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPoolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPoolsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetPoolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolsRequest.Merge(m, src)
}
func (m *GetPoolsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetPoolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolsRequest proto.InternalMessageInfo

func (m *GetPoolsRequest) GetPoolId() []uint64 {
	if m != nil {
		return m.PoolId
	}
	return nil
}

func (m *GetPoolsRequest) GetMinLiquidityCap() uint64 {
	if m != nil {
		return m.MinLiquidityCap
	}
	return 0
}

func (m *GetPoolsRequest) GetWithMarketIncentives() bool {
	if m != nil {
		return m.WithMarketIncentives
	}
	return false
}

func init() {
	proto.RegisterType((*GetPoolsRequest)(nil), "sqs.pools.GetPoolsRequest")
}

func init() { proto.RegisterFile("sqs/pools/pools.proto", fileDescriptor_a656353c33113850) }

var fileDescriptor_a656353c33113850 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc6, 0x17, 0x37, 0xa6, 0xd6, 0xc3, 0x58, 0x99, 0x6e, 0xec, 0x10, 0x86, 0x20, 0x0c, 0x0f,
	0x0b, 0x43, 0x9f, 0x40, 0x0f, 0x32, 0x50, 0x90, 0x1e, 0xbd, 0x94, 0xb4, 0x8d, 0xf5, 0x8f, 0x4b,
	0xfe, 0xed, 0x92, 0x56, 0xf6, 0x0e, 0x1e, 0x7c, 0x2c, 0x8f, 0x3b, 0x7a, 0x94, 0xf6, 0x45, 0x24,
	0x69, 0xeb, 0xe5, 0x4b, 0xbe, 0xdf, 0x2f, 0x87, 0x8f, 0x78, 0xe7, 0x3a, 0xd7, 0x2c, 0x43, 0xdc,
	0xb6, 0xb9, 0xca, 0x76, 0x68, 0xd0, 0x3f, 0xd5, 0xb9, 0x5e, 0x39, 0x30, 0x9f, 0xa4, 0x98, 0xa2,
	0xa3, 0xcc, 0xde, 0x9a, 0x07, 0xf3, 0x31, 0x97, 0xa0, 0x90, 0xb9, 0x6c, 0x11, 0x4d, 0x11, 0xd3,
	0xad, 0x60, 0xae, 0x45, 0xc5, 0x2b, 0x4b, 0x8a, 0x1d, 0x37, 0x80, 0xaa, 0xf3, 0x31, 0x6a, 0x89,
	0x9a, 0x45, 0x5c, 0x0b, 0x56, 0xae, 0x23, 0x61, 0xf8, 0x9a, 0xc5, 0x08, 0x9d, 0x9f, 0xb6, 0x5e,
	0xea, 0x94, 0x95, 0x6b, 0x7b, 0x34, 0xe2, 0xf2, 0x93, 0x78, 0xa3, 0x07, 0x61, 0x9e, 0xed, 0x9c,
	0x40, 0xe4, 0x85, 0xd0, 0xc6, 0x9f, 0x7a, 0xc7, 0x76, 0x5e, 0x08, 0xc9, 0x8c, 0x2c, 0xfa, 0xcb,
	0x41, 0x30, 0xb4, 0x75, 0x93, 0xf8, 0xd7, 0xde, 0x58, 0x82, 0x0a, 0xb7, 0x90, 0x17, 0x90, 0x80,
	0xd9, 0x87, 0x31, 0xcf, 0x66, 0x47, 0x0b, 0xb2, 0x1c, 0x04, 0x23, 0x09, 0xea, 0xb1, 0xe3, 0xf7,
	0x3c, 0xf3, 0x6f, 0xbd, 0x8b, 0x0f, 0x30, 0x6f, 0xa1, 0xe4, 0xbb, 0x77, 0x61, 0x42, 0x50, 0xb1,
	0x50, 0x06, 0x4a, 0xa1, 0x67, 0xfd, 0x05, 0x59, 0x9e, 0x04, 0x13, 0x6b, 0x9f, 0x9c, 0xdc, 0xfc,
	0xbb, 0xbb, 0xab, 0xef, 0x8a, 0x92, 0x43, 0x45, 0xc9, 0x6f, 0x45, 0xc9, 0x57, 0x4d, 0x7b, 0x87,
	0x9a, 0xf6, 0x7e, 0x6a, 0xda, 0x7b, 0x39, 0x6b, 0x3e, 0xd2, 0xec, 0x33, 0xa1, 0xa3, 0xa1, 0x1b,
	0x7f, 0xf3, 0x17, 0x00, 0x00, 0xff, 0xff, 0x62, 0x19, 0xef, 0xfc, 0x62, 0x01, 0x00, 0x00,
}

func (m *GetPoolsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPoolsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetPoolsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WithMarketIncentives {
		i--
		if m.WithMarketIncentives {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MinLiquidityCap != 0 {
		i = encodeVarintPools(dAtA, i, uint64(m.MinLiquidityCap))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PoolId) > 0 {
		dAtA2 := make([]byte, len(m.PoolId)*10)
		var j1 int
		for _, num := range m.PoolId {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintPools(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPools(dAtA []byte, offset int, v uint64) int {
	offset -= sovPools(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetPoolsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PoolId) > 0 {
		l = 0
		for _, e := range m.PoolId {
			l += sovPools(uint64(e))
		}
		n += 1 + sovPools(uint64(l)) + l
	}
	if m.MinLiquidityCap != 0 {
		n += 1 + sovPools(uint64(m.MinLiquidityCap))
	}
	if m.WithMarketIncentives {
		n += 2
	}
	return n
}

func sovPools(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPools(x uint64) (n int) {
	return sovPools(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetPoolsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPoolsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPoolsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.PoolId = append(m.PoolId, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPools
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPools
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.PoolId) == 0 {
					m.PoolId = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPools
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.PoolId = append(m.PoolId, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLiquidityCap", wireType)
			}
			m.MinLiquidityCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLiquidityCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithMarketIncentives", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithMarketIncentives = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPools(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPools
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPools
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPools
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPools
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPools        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPools          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPools = fmt.Errorf("proto: unexpected end of group")
)
