// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqs/chainregistry/v1beta1/fee_token.proto

package chainregistry

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FeeToken struct {
	// Denom is the denomination of the fee token.
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// FixedMinGasPrice is the fixed minimum gas price for the fee token.
	FixedMinGasPrice cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=fixed_min_gas_price,json=fixedMinGasPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"fixed_min_gas_price"`
	// LowGasPrice is the low gas price for the fee token.
	LowGasPrice cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=low_gas_price,json=lowGasPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"low_gas_price"`
	// AverageGasPrice is the average gas price for the fee token.
	AverageGasPrice cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=average_gas_price,json=averageGasPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"average_gas_price"`
	// HighGasPrice is the high gas price for the fee token.
	HighGasPrice cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=high_gas_price,json=highGasPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"high_gas_price"`
}

func (m *FeeToken) Reset()         { *m = FeeToken{} }
func (m *FeeToken) String() string { return proto.CompactTextString(m) }
func (*FeeToken) ProtoMessage()    {}
func (*FeeToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d3b6ba24fbcdbb1, []int{0}
}
func (m *FeeToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeToken.Merge(m, src)
}
func (m *FeeToken) XXX_Size() int {
	return m.Size()
}
func (m *FeeToken) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeToken.DiscardUnknown(m)
}

var xxx_messageInfo_FeeToken proto.InternalMessageInfo

func (m *FeeToken) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func init() {
	proto.RegisterType((*FeeToken)(nil), "sqs.chainregistry.v1beta1.FeeToken")
}

func init() {
	proto.RegisterFile("sqs/chainregistry/v1beta1/fee_token.proto", fileDescriptor_3d3b6ba24fbcdbb1)
}

var fileDescriptor_3d3b6ba24fbcdbb1 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcd, 0x6a, 0xea, 0x40,
	0x14, 0xc7, 0x93, 0xeb, 0xf5, 0x72, 0xef, 0xdc, 0x7e, 0x99, 0xba, 0x50, 0x0b, 0xb1, 0x74, 0xd5,
	0x16, 0xcc, 0x20, 0x85, 0x42, 0xb7, 0x22, 0xed, 0xa6, 0x85, 0x62, 0xbb, 0x92, 0x42, 0x98, 0xc4,
	0xe3, 0x64, 0x30, 0xc9, 0xd1, 0x4c, 0xd4, 0xfa, 0x16, 0x7d, 0x89, 0x42, 0x97, 0x5d, 0xf4, 0x21,
	0x5c, 0x4a, 0x57, 0xa5, 0x0b, 0x29, 0xba, 0xe8, 0x6b, 0x94, 0x7c, 0x28, 0xba, 0x76, 0x13, 0x72,
	0x38, 0xff, 0xf9, 0xfd, 0xce, 0xe2, 0x4f, 0x4e, 0x64, 0x4f, 0x52, 0xdb, 0x61, 0xc2, 0x0f, 0x80,
	0x0b, 0x19, 0x06, 0x23, 0x3a, 0xa8, 0x5a, 0x10, 0xb2, 0x2a, 0x6d, 0x03, 0x98, 0x21, 0x76, 0xc0,
	0x37, 0xba, 0x01, 0x86, 0xa8, 0x15, 0x65, 0x4f, 0x1a, 0x6b, 0x51, 0x23, 0x8d, 0x96, 0xf2, 0x1c,
	0x39, 0xc6, 0x29, 0x1a, 0xfd, 0x25, 0x0f, 0x4a, 0x45, 0x1b, 0xa5, 0x87, 0xd2, 0x4c, 0x16, 0xc9,
	0x90, 0xae, 0x72, 0xcc, 0x13, 0x3e, 0xd2, 0xf8, 0xbb, 0x48, 0x73, 0x44, 0xee, 0x02, 0x8d, 0x27,
	0xab, 0xdf, 0xa6, 0xcc, 0x1f, 0x25, 0xab, 0xa3, 0xe7, 0x0c, 0xf9, 0x7b, 0x09, 0x70, 0x1f, 0x1d,
	0xa3, 0xe5, 0x49, 0xb6, 0x05, 0x3e, 0x7a, 0x05, 0xf5, 0x50, 0x3d, 0xfe, 0xd7, 0x48, 0x06, 0x0d,
	0xc8, 0x7e, 0x5b, 0x3c, 0x42, 0xcb, 0xf4, 0x84, 0x6f, 0x72, 0x16, 0x49, 0x85, 0x0d, 0x85, 0x5f,
	0x51, 0xa6, 0x76, 0x3e, 0x9e, 0x96, 0x95, 0xcf, 0x69, 0xf9, 0x20, 0xb9, 0x41, 0xb6, 0x3a, 0x86,
	0x40, 0xea, 0xb1, 0xd0, 0x31, 0xae, 0x81, 0x33, 0x7b, 0x54, 0x07, 0xfb, 0xfd, 0xad, 0x42, 0xd2,
	0x13, 0xeb, 0x60, 0xbf, 0x7c, 0xbf, 0x9e, 0xaa, 0x8d, 0xbd, 0x18, 0x79, 0x23, 0xfc, 0x2b, 0x26,
	0x6f, 0x23, 0x9e, 0xd6, 0x24, 0xdb, 0x2e, 0x0e, 0x57, 0x04, 0x99, 0x8d, 0x04, 0xff, 0x5d, 0x1c,
	0x2e, 0xd9, 0x16, 0xc9, 0xb1, 0x01, 0x04, 0x8c, 0xc3, 0x0a, 0xff, 0xf7, 0x46, 0xfc, 0xdd, 0x14,
	0xb8, 0x74, 0x3c, 0x90, 0x1d, 0x47, 0x70, 0x67, 0x45, 0x90, 0xdd, 0x48, 0xb0, 0x15, 0xd1, 0x16,
	0xf4, 0xda, 0xdd, 0x78, 0xa6, 0xab, 0x93, 0x99, 0xae, 0x7e, 0xcd, 0x74, 0xf5, 0x69, 0xae, 0x2b,
	0x93, 0xb9, 0xae, 0x7c, 0xcc, 0x75, 0xa5, 0x79, 0xc1, 0x45, 0xe8, 0xf4, 0x2d, 0xc3, 0x46, 0x8f,
	0xc6, 0x08, 0x21, 0x2b, 0x2e, 0xb3, 0x24, 0x8d, 0xea, 0xd7, 0xed, 0x70, 0xca, 0xba, 0x62, 0x59,
	0xbc, 0xb5, 0x8e, 0x59, 0x7f, 0xe2, 0x0e, 0x9c, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x01, 0xc3,
	0x8a, 0x6f, 0xaa, 0x02, 0x00, 0x00,
}

func (m *FeeToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.HighGasPrice.Size()
		i -= size
		if _, err := m.HighGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeToken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.AverageGasPrice.Size()
		i -= size
		if _, err := m.AverageGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeToken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.LowGasPrice.Size()
		i -= size
		if _, err := m.LowGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeToken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.FixedMinGasPrice.Size()
		i -= size
		if _, err := m.FixedMinGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeeToken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintFeeToken(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeeToken(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeeToken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovFeeToken(uint64(l))
	}
	l = m.FixedMinGasPrice.Size()
	n += 1 + l + sovFeeToken(uint64(l))
	l = m.LowGasPrice.Size()
	n += 1 + l + sovFeeToken(uint64(l))
	l = m.AverageGasPrice.Size()
	n += 1 + l + sovFeeToken(uint64(l))
	l = m.HighGasPrice.Size()
	n += 1 + l + sovFeeToken(uint64(l))
	return n
}

func sovFeeToken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeeToken(x uint64) (n int) {
	return sovFeeToken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixedMinGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FixedMinGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LowGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AverageGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AverageGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HighGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeeToken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeeToken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeeToken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeeToken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeeToken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeeToken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeeToken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeeToken = fmt.Errorf("proto: unexpected end of group")
)
