// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqs/chainregistry/v1beta1/fee_token.proto

package chainregistry

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FeeToken struct {
	// Denom is the denomination of the fee token.
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// FixedMinGasPrice is the fixed minimum gas price for the fee token.
	FixedMinGasPrice float32 `protobuf:"fixed32,2,opt,name=fixed_min_gas_price,json=fixedMinGasPrice,proto3" json:"fixed_min_gas_price,omitempty"`
	// LowGasPrice is the low gas price for the fee token.
	LowGasPrice float32 `protobuf:"fixed32,3,opt,name=low_gas_price,json=lowGasPrice,proto3" json:"low_gas_price,omitempty"`
	// AverageGasPrice is the average gas price for the fee token.
	AverageGasPrice float32 `protobuf:"fixed32,4,opt,name=average_gas_price,json=averageGasPrice,proto3" json:"average_gas_price,omitempty"`
	// HighGasPrice is the high gas price for the fee token.
	HighGasPrice float32 `protobuf:"fixed32,5,opt,name=high_gas_price,json=highGasPrice,proto3" json:"high_gas_price,omitempty"`
}

func (m *FeeToken) Reset()         { *m = FeeToken{} }
func (m *FeeToken) String() string { return proto.CompactTextString(m) }
func (*FeeToken) ProtoMessage()    {}
func (*FeeToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d3b6ba24fbcdbb1, []int{0}
}
func (m *FeeToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeToken.Merge(m, src)
}
func (m *FeeToken) XXX_Size() int {
	return m.Size()
}
func (m *FeeToken) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeToken.DiscardUnknown(m)
}

var xxx_messageInfo_FeeToken proto.InternalMessageInfo

func (m *FeeToken) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *FeeToken) GetFixedMinGasPrice() float32 {
	if m != nil {
		return m.FixedMinGasPrice
	}
	return 0
}

func (m *FeeToken) GetLowGasPrice() float32 {
	if m != nil {
		return m.LowGasPrice
	}
	return 0
}

func (m *FeeToken) GetAverageGasPrice() float32 {
	if m != nil {
		return m.AverageGasPrice
	}
	return 0
}

func (m *FeeToken) GetHighGasPrice() float32 {
	if m != nil {
		return m.HighGasPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*FeeToken)(nil), "sqs.chainregistry.v1beta1.FeeToken")
}

func init() {
	proto.RegisterFile("sqs/chainregistry/v1beta1/fee_token.proto", fileDescriptor_3d3b6ba24fbcdbb1)
}

var fileDescriptor_3d3b6ba24fbcdbb1 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xbf, 0x4e, 0xc2, 0x50,
	0x14, 0xc7, 0xf1, 0x5e, 0x14, 0xa3, 0xd7, 0xff, 0xd5, 0x01, 0x97, 0x1b, 0x42, 0x1c, 0xd0, 0x84,
	0xde, 0x10, 0x27, 0x57, 0x07, 0x9d, 0x4c, 0x0c, 0x3a, 0xb9, 0x34, 0xb7, 0xe5, 0x70, 0x7b, 0x42,
	0xdb, 0x5b, 0x7a, 0x2a, 0xe8, 0x5b, 0xf8, 0x52, 0x26, 0x8e, 0x8c, 0x8e, 0xa6, 0x7d, 0x11, 0xd3,
	0x0a, 0x4d, 0x19, 0xcf, 0xf9, 0x7d, 0xa6, 0x2f, 0xbf, 0xa2, 0x19, 0x49, 0x3f, 0x50, 0x18, 0xa7,
	0xa0, 0x91, 0xb2, 0xf4, 0x43, 0xce, 0x87, 0x1e, 0x64, 0x6a, 0x28, 0x27, 0x00, 0x6e, 0x66, 0xa6,
	0x10, 0x3b, 0x49, 0x6a, 0x32, 0x63, 0x5f, 0xd0, 0x8c, 0x9c, 0x0d, 0xea, 0xac, 0x68, 0xef, 0x8b,
	0xf1, 0xdd, 0x7b, 0x80, 0x97, 0x52, 0xdb, 0xe7, 0xbc, 0x3d, 0x86, 0xd8, 0x44, 0x1d, 0xd6, 0x65,
	0xfd, 0xbd, 0xd1, 0xff, 0x61, 0x0f, 0xf8, 0xd9, 0x04, 0xdf, 0x61, 0xec, 0x46, 0x18, 0xbb, 0x5a,
	0x91, 0x9b, 0xa4, 0xe8, 0x43, 0xa7, 0xd5, 0x65, 0xfd, 0xd6, 0xe8, 0xa4, 0x9a, 0x1e, 0x31, 0x7e,
	0x50, 0xf4, 0x54, 0xfe, 0xed, 0x1e, 0x3f, 0x0c, 0xcd, 0xa2, 0x01, 0xb7, 0x2a, 0xb8, 0x1f, 0x9a,
	0x45, 0x6d, 0xae, 0xf9, 0xa9, 0x9a, 0x43, 0xaa, 0x34, 0x34, 0xdc, 0x76, 0xe5, 0x8e, 0x57, 0x43,
	0x6d, 0x2f, 0xf9, 0x51, 0x80, 0x3a, 0x68, 0xc0, 0x76, 0x05, 0x0f, 0xca, 0xef, 0x5a, 0xdd, 0x3d,
	0x7f, 0xe7, 0x82, 0x2d, 0x73, 0xc1, 0x7e, 0x73, 0xc1, 0x3e, 0x0b, 0x61, 0x2d, 0x0b, 0x61, 0xfd,
	0x14, 0xc2, 0x7a, 0xbd, 0xd5, 0x98, 0x05, 0x6f, 0x9e, 0xe3, 0x9b, 0x48, 0x1a, 0x8a, 0x0c, 0x21,
	0x0d, 0x42, 0xe5, 0x91, 0x2c, 0xfb, 0x25, 0x53, 0x2d, 0x55, 0x82, 0x75, 0xb9, 0x8d, 0x48, 0xde,
	0x4e, 0x95, 0xef, 0xe6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x37, 0xa5, 0x9b, 0xa5, 0x6b, 0x01, 0x00,
	0x00,
}

func (m *FeeToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HighGasPrice != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.HighGasPrice))))
		i--
		dAtA[i] = 0x2d
	}
	if m.AverageGasPrice != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.AverageGasPrice))))
		i--
		dAtA[i] = 0x25
	}
	if m.LowGasPrice != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.LowGasPrice))))
		i--
		dAtA[i] = 0x1d
	}
	if m.FixedMinGasPrice != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.FixedMinGasPrice))))
		i--
		dAtA[i] = 0x15
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintFeeToken(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeeToken(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeeToken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovFeeToken(uint64(l))
	}
	if m.FixedMinGasPrice != 0 {
		n += 5
	}
	if m.LowGasPrice != 0 {
		n += 5
	}
	if m.AverageGasPrice != 0 {
		n += 5
	}
	if m.HighGasPrice != 0 {
		n += 5
	}
	return n
}

func sovFeeToken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeeToken(x uint64) (n int) {
	return sovFeeToken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixedMinGasPrice", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.FixedMinGasPrice = float32(math.Float32frombits(v))
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowGasPrice", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.LowGasPrice = float32(math.Float32frombits(v))
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field AverageGasPrice", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.AverageGasPrice = float32(math.Float32frombits(v))
		case 5:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighGasPrice", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.HighGasPrice = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipFeeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeeToken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeeToken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeeToken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeeToken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeeToken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeeToken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeeToken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeeToken = fmt.Errorf("proto: unexpected end of group")
)
