# This workflow builds the binary and run tests

name: Build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "v[0-9]**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v4
    -
      name: 🐿 Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    -
      name: Build
      run: go build -v ./...
    -
      name: Test
      shell: bash
      run: |
        set -o pipefail
        go test -v ./... -coverprofile=coverage.out -covermode=count -json | tee report.json

    - name: Archive code coverage results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: |
          coverage.out
          report.json
